services:
  # 评论系统API服务
  comment_api:
    build: .
    container_name: comment-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://comment_user:comment_pass@postgres:5432/comment_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-production-secret-key-change-this
      - CORS_ORIGINS=["http://localhost:3000", "https://www.yhnotes.com"]
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - comment-network

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: comment-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=comment_db
      - POSTGRES_USER=comment_user
      - POSTGRES_PASSWORD=comment_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comment_user -d comment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - comment-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: comment-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - comment-network

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: comment-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    depends_on:
      - comment_api
    networks:
      - comment-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  comment-network:
    driver: bridge